<?php

return [
    'all' => [
        'dashboard.view',
        'stats.view',
        'orders.view',
        'orders.manage',
        'payments.view',
        'payments.resync',
        'products.view',
        'products.manage',
        'categories.manage',
        'promotions.manage',
        'coupons.manage',
        'subscriptions.manage',
        'premium.manage',
        'redeems.view',
        'redeems.manage',
        'stock.manage',
        'sourcing.view',
        'sourcing.manage',
        'users.view',
        'users.manage',
        'support.view',
        'support.manage',
        'email.view',
        'email.manage',
        'reviews.view',
        'settings.manage',
        'notifications.manage',
        'audit.view',
        'wallet.manage',
        'tournaments.view',
        'tournaments.manage',

        // Gaming Account Marketplace
        'marketplace.sellers.view',
        'marketplace.sellers.manage',
        'marketplace.withdraws.manage',
        'marketplace.disputes.manage',
        'marketplace.listings.manage',
        'marketplace.orders.manage',
        'marketplace.settings.manage',
    ],
    'roles' => [
        'admin_super' => ['*'],
        'admin' => ['*'],
        'admin_operations' => [
            'dashboard.view',
            'stats.view',
            'orders.view',
            'orders.manage',
            'payments.view',
            'payments.resync',
            'subscriptions.manage',
            'premium.manage',
            'redeems.view',
            'redeems.manage',
            'stock.manage',
            'sourcing.view',
            'sourcing.manage',
            'email.view',
            'email.manage',
            'notifications.manage',
            'wallet.manage',

            'marketplace.sellers.view',
            'marketplace.sellers.manage',
            'marketplace.listings.manage',
            'marketplace.orders.manage',
            'marketplace.withdraws.manage',
        ],
        'admin_domain' => [
            'dashboard.view',
            'users.view',
            'orders.view',
            'payments.view',
            'email.view',
            'email.manage',
            'notifications.manage',
            'premium.manage',
            'tournaments.view',
            'tournaments.manage',

            'marketplace.sellers.view',
            'marketplace.sellers.manage',
            'marketplace.disputes.manage',
            'marketplace.settings.manage',
        ],
        'admin_manager' => [
            'dashboard.view',
            'stats.view',
            'orders.view',
            'orders.manage',
            'payments.view',
            'payments.resync',
            'products.view',
            'products.manage',
            'categories.manage',
            'premium.manage',
            'redeems.view',
            'redeems.manage',
            'stock.manage',
            'sourcing.view',
            'sourcing.manage',
            'email.view',
            'email.manage',
            'notifications.manage',
            'wallet.manage',

            'marketplace.sellers.view',
            'marketplace.sellers.manage',
            'marketplace.withdraws.manage',
            'marketplace.disputes.manage',
            'marketplace.listings.manage',
            'marketplace.orders.manage',
            'marketplace.settings.manage',
        ],
        'admin_support' => [
            'dashboard.view',
            'orders.view',
            'users.view',
            'support.view',
            'support.manage',
            'email.view',
            'email.manage',
            'reviews.view',
            'wallet.manage',

            'marketplace.sellers.view',
        ],
        'admin_marketing' => [
            'dashboard.view',
            'stats.view',
            'products.view',
            'promotions.manage',
            'coupons.manage',
            'subscriptions.manage',
            'premium.manage',
        ],
        'admin_article' => [
            'dashboard.view',
            'products.view',
            'products.manage',
            'sourcing.view',
            'tournaments.view',
        ],
        'admin_client' => [
            'dashboard.view',
            'orders.view',
            'payments.view',
            'users.view',
            'email.view',
            'email.manage',
            'wallet.manage',

            'marketplace.sellers.view',
        ],
        'staff' => [
            'dashboard.view',
            'orders.view',
            'payments.view',
            'products.view',
            'sourcing.view',

            'marketplace.sellers.view',
        ],
        'viewer' => [
            'dashboard.view',
            'stats.view',
            'orders.view',
            'payments.view',
            'products.view',
            'sourcing.view',
            'tournaments.view',

            'marketplace.sellers.view',
        ],
    ],
];
