<?php

return [
    'all' => [
        'dashboard.view',
        'stats.view',
        'orders.view',
        'orders.manage',
        'payments.view',
        'payments.resync',
        'products.view',
        'products.manage',
        'categories.manage',
        'promotions.manage',
        'coupons.manage',
        'subscriptions.manage',
        'redeems.view',
        'redeems.manage',
        'stock.manage',
        'users.view',
        'users.manage',
        'support.view',
        'support.manage',
        'email.view',
        'email.manage',
        'reviews.view',
        'settings.manage',
        'audit.view',
    ],
    'roles' => [
        'admin_super' => ['*'],
        'admin' => ['*'],
        'admin_manager' => [
            'dashboard.view',
            'stats.view',
            'orders.view',
            'orders.manage',
            'payments.view',
            'payments.resync',
            'products.view',
            'products.manage',
            'categories.manage',
            'redeems.view',
            'redeems.manage',
            'stock.manage',
            'email.view',
        ],
        'admin_support' => [
            'dashboard.view',
            'orders.view',
            'users.view',
            'support.view',
            'support.manage',
            'email.view',
            'reviews.view',
        ],
        'admin_marketing' => [
            'dashboard.view',
            'stats.view',
            'products.view',
            'promotions.manage',
            'coupons.manage',
            'subscriptions.manage',
        ],
        'admin_article' => [
            'dashboard.view',
            'products.view',
            'products.manage',
        ],
        'admin_client' => [
            'dashboard.view',
            'orders.view',
            'payments.view',
            'users.view',
            'email.view',
        ],
        'staff' => [
            'dashboard.view',
            'orders.view',
            'payments.view',
            'products.view',
        ],
        'viewer' => [
            'dashboard.view',
            'stats.view',
            'orders.view',
            'payments.view',
            'products.view',
        ],
    ],
];
