<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'cinetpay' => [
        'api_key' => env('CINETPAY_API_KEY'),
        'site_id' => env('CINETPAY_SITE_ID'),
        'secret' => env('CINETPAY_SECRET'),
        'webhook_secret' => env('CINETPAY_WEBHOOK_SECRET', env('CINETPAY_SECRET')),
        'transfer_webhook_secret' => env('CINETPAY_TRANSFER_WEBHOOK_SECRET', env('CINETPAY_SECRET')),
        'base_url' => env('CINETPAY_BASE_URL', 'https://api-checkout.cinetpay.com/v2'),
    ],

    'discord' => [
        'webhook' => env('DISCORD_WEBHOOK_URL'),
    ],

    'play_integrity' => [
        'package_name' => env('PLAY_INTEGRITY_PACKAGE_NAME', 'space.primegaming.app'),
        'service_account_json' => env('PLAY_INTEGRITY_SERVICE_ACCOUNT_JSON'),
        'service_account_path' => env('PLAY_INTEGRITY_SERVICE_ACCOUNT_PATH'),
    ],

    'brevo' => [
        'api_key' => env('BREVO_API_KEY'),
        'base_url' => env('BREVO_BASE_URL', 'https://api.brevo.com'),
    ],

    'paypal' => [
        'client_id' => env('PAYPAL_CLIENT_ID'),
        'client_secret' => env('PAYPAL_CLIENT_SECRET'),
        'environment' => env('PAYPAL_ENV', 'sandbox'),
        'base_url' => env('PAYPAL_BASE_URL'),
    ],

    'sourcing' => [
        'oauth_state_ttl_minutes' => (int) env('SOURCING_OAUTH_STATE_TTL_MINUTES', 15),
        'platforms' => [
            'alibaba' => [
                'authorize_url' => env('ALIBABA_OAUTH_AUTHORIZE_URL', 'https://openapi-auth.alibaba.com/oauth/authorize'),
                'token_url' => env('ALIBABA_OAUTH_TOKEN_URL', 'https://openapi-api.alibaba.com/rest/auth/token/create'),
                'security_token_url' => env('ALIBABA_OAUTH_SECURITY_TOKEN_URL', 'https://openapi-api.alibaba.com/rest/auth/token/security/create'),
                'refresh_url' => env('ALIBABA_OAUTH_REFRESH_URL', 'https://openapi-api.alibaba.com/rest/auth/token/refresh'),
                'security_refresh_url' => env('ALIBABA_OAUTH_SECURITY_REFRESH_URL', 'https://openapi-api.alibaba.com/rest/auth/token/security/refresh'),
                'api_base_url' => env('ALIBABA_API_BASE_URL', 'https://openapi-api.alibaba.com'),
                'callback_url' => env('ALIBABA_CALLBACK_URL'),
                'default_scope' => env('ALIBABA_DEFAULT_SCOPE'),
                'include_optional_authorize_params' => env('ALIBABA_INCLUDE_OPTIONAL_AUTHORIZE_PARAMS', false),
                'authorize_force_auth' => env('ALIBABA_AUTHORIZE_FORCE_AUTH', false),
                'authorize_uuid' => env('ALIBABA_AUTHORIZE_UUID'),
                'prefer_security_tokens' => env('ALIBABA_PREFER_SECURITY_TOKENS', false),
                'sign_method' => env('ALIBABA_SIGN_METHOD', 'sha256'),
                'product_detail_method' => env('ALIBABA_PRODUCT_DETAIL_METHOD', env('ALIBABA_PRODUCT_DETAIL_PATH', '/alibaba/icbu/product/get/v2')),
                'product_lookup_param' => env('ALIBABA_PRODUCT_LOOKUP_PARAM', 'product_id'),
                'product_search_method' => env('ALIBABA_PRODUCT_SEARCH_METHOD', '/alibaba/icbu/product/search/v2'),
                'category_predict_method' => env('ALIBABA_CATEGORY_PREDICT_METHOD', '/alibaba/icbu/category/predict/v2'),
                'video_upload_method' => env('ALIBABA_VIDEO_UPLOAD_METHOD', '/alibaba/icbu/video/upload'),
                'video_upload_result_method' => env('ALIBABA_VIDEO_UPLOAD_RESULT_METHOD', '/alibaba/icbu/video/upload/result'),
                'video_query_method' => env('ALIBABA_VIDEO_QUERY_METHOD', '/alibaba/icbu/video/query'),
                'video_relation_main_method' => env('ALIBABA_VIDEO_RELATION_MAIN_METHOD', '/alibaba/icbu/video/relation/product/main'),
                'buyer_item_add_method' => env('ALIBABA_BUYER_ITEM_ADD_METHOD', '/eco/buyer/item/add'),
                'buyer_item_query_method' => env('ALIBABA_BUYER_ITEM_QUERY_METHOD', '/eco/buyer/item/query'),
                'buyer_item_update_method' => env('ALIBABA_BUYER_ITEM_UPDATE_METHOD', '/eco/buyer/item/update'),
                'buyer_item_delete_method' => env('ALIBABA_BUYER_ITEM_DELETE_METHOD', '/eco/buyer/item/delete'),
                'buyer_product_events_method' => env('ALIBABA_BUYER_PRODUCT_EVENTS_METHOD', '/eco/buyer/product/events'),
                'buyer_product_channel_batch_import_method' => env('ALIBABA_BUYER_PRODUCT_CHANNEL_BATCH_IMPORT_METHOD', '/eco/buyer/product/channel/batch-import'),
                'buyer_crossborder_product_check_method' => env('ALIBABA_BUYER_CROSSBORDER_PRODUCT_CHECK_METHOD', '/eco/buyer/crossborder/product/check'),
                'buyer_product_cert_method' => env('ALIBABA_BUYER_PRODUCT_CERT_METHOD', '/eco/buyer/product/cert'),
                'buyer_product_description_method' => env('ALIBABA_BUYER_PRODUCT_DESCRIPTION_METHOD', '/eco/buyer/product/description'),
                'buyer_product_keyattributes_method' => env('ALIBABA_BUYER_PRODUCT_KEYATTRIBUTES_METHOD', '/eco/buyer/product/keyattributes'),
                'buyer_product_inventory_method' => env('ALIBABA_BUYER_PRODUCT_INVENTORY_METHOD', '/eco/buyer/product/inventory'),
                'buyer_local_product_check_method' => env('ALIBABA_BUYER_LOCAL_PRODUCT_CHECK_METHOD', '/eco/buyer/local/product/check'),
                'buyer_localregular_product_check_method' => env('ALIBABA_BUYER_LOCALREGULAR_PRODUCT_CHECK_METHOD', '/eco/buyer/localregular/product/check'),
                'buyer_item_rec_image_method' => env('ALIBABA_BUYER_ITEM_REC_IMAGE_METHOD', '/eco/buyer/item/rec/image'),
                'buyer_product_check_method' => env('ALIBABA_BUYER_PRODUCT_CHECK_METHOD', '/eco/buyer/product/check'),
                'buyer_product_search_method' => env('ALIBABA_BUYER_PRODUCT_SEARCH_METHOD', '/eco/buyer/product/search'),
                'buyer_item_rec_method' => env('ALIBABA_BUYER_ITEM_REC_METHOD', '/eco/buyer/item/rec'),
                'advanced_freight_calculate_method' => env('ALIBABA_ADVANCED_FREIGHT_CALCULATE_METHOD', '/order/freight/calculate'),
                'basic_freight_calculate_method' => env('ALIBABA_BASIC_FREIGHT_CALCULATE_METHOD', '/shipping/freight/calculate'),
                'merge_pay_query_method' => env('ALIBABA_MERGE_PAY_QUERY_METHOD', '/order/merge/pay/query'),
                'buynow_order_create_method' => env('ALIBABA_BUYNOW_ORDER_CREATE_METHOD', '/buynow/order/create'),
                'logistics_tracking_get_method' => env('ALIBABA_LOGISTICS_TRACKING_GET_METHOD', '/order/logistics/tracking/get'),
                'overseas_admittance_check_method' => env('ALIBABA_OVERSEAS_ADMITTANCE_CHECK_METHOD', '/icbu/check/overseas/admittance'),
                'dropshipping_order_pay_method' => env('ALIBABA_DROPSHIPPING_ORDER_PAY_METHOD', '/alibaba/dropshipping/order/pay'),
                'order_fund_query_method' => env('ALIBABA_ORDER_FUND_QUERY_METHOD', '/alibaba/order/fund/query'),
                'ggs_warehouse_list_method' => env('ALIBABA_GGS_WAREHOUSE_LIST_METHOD', '/alibaba/ggs/warehouse/list'),
                'order_attachment_upload_method' => env('ALIBABA_ORDER_ATTACHMENT_UPLOAD_METHOD', '/alibaba/order/attachment/upload'),
                'order_cancel_method' => env('ALIBABA_ORDER_CANCEL_METHOD', '/alibaba/order/cancel'),
                'order_get_method' => env('ALIBABA_ORDER_GET_METHOD', '/alibaba/order/get'),
                'order_list_method' => env('ALIBABA_ORDER_LIST_METHOD', '/alibaba/order/list'),
                'order_pay_result_query_method' => env('ALIBABA_ORDER_PAY_RESULT_QUERY_METHOD', '/alibaba/order/pay/result/query'),
                'seller_warehouse_list_method' => env('ALIBABA_SELLER_WAREHOUSE_LIST_METHOD', '/warehouse/list'),
                'order_logistics_query_method' => env('ALIBABA_ORDER_LOGISTICS_QUERY_METHOD', '/order/logistics/query'),
                'timeout' => (int) env('ALIBABA_REQUEST_TIMEOUT', 20),
            ],
            'aliexpress' => [
                'authorize_url' => env('ALIEXPRESS_OAUTH_AUTHORIZE_URL', 'https://api-sg.aliexpress.com/oauth/authorize'),
                'token_url' => env('ALIEXPRESS_OAUTH_TOKEN_URL', 'https://api-sg.aliexpress.com/rest/auth/token/create'),
                'security_token_url' => env('ALIEXPRESS_OAUTH_SECURITY_TOKEN_URL', 'https://api-sg.aliexpress.com/rest/auth/token/security/create'),
                'refresh_url' => env('ALIEXPRESS_OAUTH_REFRESH_URL', 'https://api-sg.aliexpress.com/rest/auth/token/refresh'),
                'security_refresh_url' => env('ALIEXPRESS_OAUTH_SECURITY_REFRESH_URL', 'https://api-sg.aliexpress.com/rest/auth/token/security/refresh'),
                'api_base_url' => env('ALIEXPRESS_API_BASE_URL', 'https://api-sg.aliexpress.com'),
                'callback_url' => env('ALIEXPRESS_CALLBACK_URL'),
                'default_scope' => env('ALIEXPRESS_DEFAULT_SCOPE'),
                'include_optional_authorize_params' => env('ALIEXPRESS_INCLUDE_OPTIONAL_AUTHORIZE_PARAMS', false),
                'authorize_force_auth' => env('ALIEXPRESS_AUTHORIZE_FORCE_AUTH', false),
                'authorize_uuid' => env('ALIEXPRESS_AUTHORIZE_UUID'),
                'prefer_security_tokens' => env('ALIEXPRESS_PREFER_SECURITY_TOKENS', true),
                'sign_method' => env('ALIEXPRESS_SIGN_METHOD', 'sha256'),
                'local_test_force_credentials' => env('ALIEXPRESS_LOCAL_TEST_FORCE_CREDENTIALS', false),
                'local_test_app_key' => env('ALIEXPRESS_LOCAL_TEST_APP_KEY'),
                'local_test_app_secret' => env('ALIEXPRESS_LOCAL_TEST_APP_SECRET'),
                'local_test_access_token' => env('ALIEXPRESS_LOCAL_TEST_ACCESS_TOKEN'),
                'local_test_refresh_token' => env('ALIEXPRESS_LOCAL_TEST_REFRESH_TOKEN'),
                'product_detail_method' => env('ALIEXPRESS_PRODUCT_DETAIL_METHOD', env('ALIEXPRESS_PRODUCT_DETAIL_PATH', 'aliexpress.solution.product.info.get')),
                'product_search_method' => env('ALIEXPRESS_PRODUCT_SEARCH_METHOD', 'aliexpress.solution.product.list.get'),
                'category_tree_method' => env('ALIEXPRESS_CATEGORY_TREE_METHOD', 'aliexpress.solution.seller.category.tree.query'),
                'ds_order_create_method' => env('ALIEXPRESS_DS_ORDER_CREATE_METHOD', 'aliexpress.ds.order.create'),
                'ds_product_get_method' => env('ALIEXPRESS_DS_PRODUCT_GET_METHOD', 'aliexpress.ds.product.get'),
                'ds_product_wholesale_get_method' => env('ALIEXPRESS_DS_PRODUCT_WHOLESALE_GET_METHOD', 'aliexpress.ds.product.wholesale.get'),
                'ds_image_search_v2_method' => env('ALIEXPRESS_DS_IMAGE_SEARCH_V2_METHOD', 'aliexpress.ds.image.searchV2'),
                'ds_category_get_method' => env('ALIEXPRESS_DS_CATEGORY_GET_METHOD', 'aliexpress.ds.category.get'),
                'ds_feed_itemids_get_method' => env('ALIEXPRESS_DS_FEED_ITEMIDS_GET_METHOD', 'aliexpress.ds.feed.itemids.get'),
                'ds_member_benefit_get_method' => env('ALIEXPRESS_DS_MEMBER_BENEFIT_GET_METHOD', 'aliexpress.ds.member.benefit.get'),
                'ds_default_logistics_service_name' => env('ALIEXPRESS_DS_DEFAULT_LOGISTICS_SERVICE_NAME', 'AliExpress Selection Standard'),
                'buyer_freight_calculate_method' => env('ALIEXPRESS_BUYER_FREIGHT_CALCULATE_METHOD', 'aliexpress.logistics.buyer.freight.calculate'),
                'ds_trade_order_get_method' => env('ALIEXPRESS_DS_TRADE_ORDER_GET_METHOD', 'aliexpress.trade.ds.order.get'),
                'ds_order_tracking_get_method' => env('ALIEXPRESS_DS_ORDER_TRACKING_GET_METHOD', 'aliexpress.ds.order.tracking.get'),
                'order_get_method' => env('ALIEXPRESS_ORDER_GET_METHOD', 'aliexpress.trade.new.redefining.findorderbyid'),
                'order_list_method' => env('ALIEXPRESS_ORDER_LIST_METHOD', 'aliexpress.trade.seller.orderlist.get'),
                'affiliate_shipping_method' => env('ALIEXPRESS_AFFILIATE_SHIPPING_METHOD', 'aliexpress.affiliate.product.shipping.get'),
                'affiliate_sku_detail_method' => env('ALIEXPRESS_AFFILIATE_SKU_DETAIL_METHOD', 'aliexpress.affiliate.product.sku.detail.get'),
                'affiliate_product_detail_method' => env('ALIEXPRESS_AFFILIATE_PRODUCT_DETAIL_METHOD', 'aliexpress.affiliate.productdetail.get'),
                'affiliate_product_query_method' => env('ALIEXPRESS_AFFILIATE_PRODUCT_QUERY_METHOD', 'aliexpress.affiliate.product.query'),
                'affiliate_category_get_method' => env('ALIEXPRESS_AFFILIATE_CATEGORY_GET_METHOD', 'aliexpress.affiliate.category.get'),
                'affiliate_link_generate_method' => env('ALIEXPRESS_AFFILIATE_LINK_GENERATE_METHOD', 'aliexpress.affiliate.link.generate'),
                'affiliate_order_get_method' => env('ALIEXPRESS_AFFILIATE_ORDER_GET_METHOD', 'aliexpress.affiliate.order.get'),
                'affiliate_order_list_method' => env('ALIEXPRESS_AFFILIATE_ORDER_LIST_METHOD', 'aliexpress.affiliate.order.list'),
                'affiliate_order_listbyindex_method' => env('ALIEXPRESS_AFFILIATE_ORDER_LISTBYINDEX_METHOD', 'aliexpress.affiliate.order.listbyindex'),
                'affiliate_hotproduct_query_method' => env('ALIEXPRESS_AFFILIATE_HOTPRODUCT_QUERY_METHOD', 'aliexpress.affiliate.hotproduct.query'),
                'affiliate_hotproduct_download_method' => env('ALIEXPRESS_AFFILIATE_HOTPRODUCT_DOWNLOAD_METHOD', 'aliexpress.affiliate.hotproduct.download'),
                'affiliate_product_smartmatch_method' => env('ALIEXPRESS_AFFILIATE_PRODUCT_SMARTMATCH_METHOD', 'aliexpress.affiliate.product.smartmatch'),
                'seller_invoicing_apply_info_get_method' => env('ALIEXPRESS_SELLER_INVOICING_APPLY_INFO_GET_METHOD', 'aliexpress.trade.invoice.sellerInvoicingApplyInfo.get'),
                'fund_merchant_orderdetail_method' => env('ALIEXPRESS_FUND_MERCHANT_ORDERDETAIL_METHOD', 'aliexpress.fund.merchant.orderdetail'),
                'brazil_invoice_query_method' => env('ALIEXPRESS_BRAZIL_INVOICE_QUERY_METHOD', 'aliexpress.trade.tax.invoice.queryBrazilInvoiceInfo'),
                'brazil_invoice_upload_method' => env('ALIEXPRESS_BRAZIL_INVOICE_UPLOAD_METHOD', 'aliexpress.trade.tax.invoice.UploadBrazilInvoice'),
                'seller_invoicing_result_push_method' => env('ALIEXPRESS_SELLER_INVOICING_RESULT_PUSH_METHOD', 'aliexpress.trade.invoice.sellerInvoicingResult.push'),
                'hscode_query_regulatory_attributes_method' => env('ALIEXPRESS_HSCODE_QUERY_REGULATORY_ATTRIBUTES_METHOD', 'aliexpress.trade.tax.hscode.queryRegulatoryAttributesInfoWithHsCode'),
                'hscode_select_regulatory_attributes_options_method' => env('ALIEXPRESS_HSCODE_SELECT_REGULATORY_ATTRIBUTES_OPTIONS_METHOD', 'aliexpress.trade.tax.hscode.selectRegulatoryAttributesOptions'),
                'fund_recipet_flowdetail_query_method' => env('ALIEXPRESS_FUND_RECIPET_FLOWDETAIL_QUERY_METHOD', 'aliexpress.fund.merchant.recipet.flowdetail.query'),
                'fund_recipet_config_query_method' => env('ALIEXPRESS_FUND_RECIPET_CONFIG_QUERY_METHOD', 'aliexpress.fund.merchant.recipet.config.query'),
                'fund_recipet_debt_query_method' => env('ALIEXPRESS_FUND_RECIPET_DEBT_QUERY_METHOD', 'aliexpress.fund.merchant.recipet.debt.query'),
                'customize_product_info_query_method' => env('ALIEXPRESS_CUSTOMIZE_PRODUCT_INFO_QUERY_METHOD', 'aliexpress.customize.product.info.query'),
                'customize_product_template_query_method' => env('ALIEXPRESS_CUSTOMIZE_PRODUCT_TEMPLATE_QUERY_METHOD', 'aliexpress.customize.product.template.query'),
                'customize_product_info_audit_result_query_method' => env('ALIEXPRESS_CUSTOMIZE_PRODUCT_INFO_AUDIT_RESULT_QUERY_METHOD', 'aliexpress.customize.product.info.audit.result.query'),
                'customize_product_info_create_method' => env('ALIEXPRESS_CUSTOMIZE_PRODUCT_INFO_CREATE_METHOD', 'aliexpress.customize.product.info.create'),
                'local_cb_product_prices_edit_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCT_PRICES_EDIT_METHOD', 'aliexpress.offer.local.cb.product.prices.edit'),
                'local_cb_product_status_update_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCT_STATUS_UPDATE_METHOD', 'aliexpress.offer.local.cb.product.status.update'),
                'local_cb_product_edit_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCT_EDIT_METHOD', 'aliexpress.offer.local.cb.product.edit'),
                'local_cb_products_list_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCTS_LIST_METHOD', 'aliexpress.offer.local.cb.products.list'),
                'local_cb_product_post_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCT_POST_METHOD', 'aliexpress.offer.local.cb.product.post'),
                'local_cb_products_stock_edit_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCTS_STOCK_EDIT_METHOD', 'aliexpress.offer.local.cb.products.stock.edit'),
                'local_cb_product_query_method' => env('ALIEXPRESS_LOCAL_CB_PRODUCT_QUERY_METHOD', 'aliexpress.offer.local.cb.product.query'),
                'category_child_attributes_query_method' => env('ALIEXPRESS_CATEGORY_CHILD_ATTRIBUTES_QUERY_METHOD', 'aliexpress.category.redefining.getchildattributesresultbypostcateidandpath'),
                'category_tree_list_method' => env('ALIEXPRESS_CATEGORY_TREE_LIST_METHOD', 'aliexpress.category.tree.list'),
                'category_item_qualification_list_method' => env('ALIEXPRESS_CATEGORY_ITEM_QUALIFICATION_LIST_METHOD', 'aliexpress.category.itemQualification.list'),
                'category_cascade_properties_query_method' => env('ALIEXPRESS_CATEGORY_CASCADE_PROPERTIES_QUERY_METHOD', 'aliexpress.category.redefining.queryCascadeProperties'),
                'solution_sku_attribute_query_method' => env('ALIEXPRESS_SOLUTION_SKU_ATTRIBUTE_QUERY_METHOD', 'aliexpress.solution.sku.attribute.query'),
                'seller_category_tree_query_method' => env('ALIEXPRESS_SELLER_CATEGORY_TREE_QUERY_METHOD', 'aliexpress.solution.seller.category.tree.query'),
                'category_qualifications_list_method' => env('ALIEXPRESS_CATEGORY_QUALIFICATIONS_LIST_METHOD', 'aliexpress.category.qualifications.list'),
                'freight_seller_intention_query_method' => env('ALIEXPRESS_FREIGHT_SELLER_INTENTION_QUERY_METHOD', 'aliexpress.freight.redefining.querySellerIntention'),
                'freight_isv_gray_query_method' => env('ALIEXPRESS_FREIGHT_ISV_GRAY_QUERY_METHOD', 'aliexpress.freight.redefining.queryInIsvGray'),
                'freight_template_recommend_method' => env('ALIEXPRESS_FREIGHT_TEMPLATE_RECOMMEND_METHOD', 'aliexpress.freight.redefining.recommendFreightTemplate'),
                'freight_template_create_method' => env('ALIEXPRESS_FREIGHT_TEMPLATE_CREATE_METHOD', 'aliexpress.freight.redefining.createFreightTemplate'),
                'freight_template_list_method' => env('ALIEXPRESS_FREIGHT_TEMPLATE_LIST_METHOD', 'aliexpress.freight.redefining.listfreighttemplate'),
                'trade_order_decrypt_method' => env('ALIEXPRESS_TRADE_ORDER_DECRYPT_METHOD', 'aliexpress.trade.seller.order.decrypt'),
                'solution_order_receiptinfo_get_method' => env('ALIEXPRESS_SOLUTION_ORDER_RECEIPTINFO_GET_METHOD', 'aliexpress.solution.order.receiptinfo.get'),
                'solution_order_get_method' => env('ALIEXPRESS_SOLUTION_ORDER_GET_METHOD', 'aliexpress.solution.order.get'),
                'trade_verifycode_method' => env('ALIEXPRESS_TRADE_VERIFYCODE_METHOD', 'aliexpress.trade.redefining.verifycode'),
                'trade_confirmshippingmode_method' => env('ALIEXPRESS_TRADE_CONFIRMSHIPPINGMODE_METHOD', 'aliexpress.trade.redefining.confirmshippingmode'),
                'trade_sendcode_method' => env('ALIEXPRESS_TRADE_SENDCODE_METHOD', 'aliexpress.trade.redefining.sendcode'),
                'asf_local2local_sub_declareship_method' => env('ALIEXPRESS_ASF_LOCAL2LOCAL_SUB_DECLARESHIP_METHOD', 'aliexpress.asf.local2local.sub.declareship'),
                'asf_dbs_declareship_method' => env('ALIEXPRESS_ASF_DBS_DECLARESHIP_METHOD', 'aliexpress.asf.dbs.declareship'),
                'asf_local2local_self_pickup_declareship_method' => env('ALIEXPRESS_ASF_LOCAL2LOCAL_SELF_PICKUP_DECLARESHIP_METHOD', 'aliexpress.asf.local2local.self.pickup.declareship'),
                'asf_dbs_declare_ship_modify_method' => env('ALIEXPRESS_ASF_DBS_DECLARE_SHIP_MODIFY_METHOD', 'aliexpress.asf.dbs.declare.ship.modify'),
                'asf_shipment_pack_method' => env('ALIEXPRESS_ASF_SHIPMENT_PACK_METHOD', 'aliexpress.asf.shipment.pack'),
                'asf_order_shipping_service_get_method' => env('ALIEXPRESS_ASF_ORDER_SHIPPING_SERVICE_GET_METHOD', 'aliexpress.asf.order.shipping.service.get'),
                'asf_package_shipping_service_get_method' => env('ALIEXPRESS_ASF_PACKAGE_SHIPPING_SERVICE_GET_METHOD', 'aliexpress.asf.package.shipping.service.get'),
                'asf_local2local_split_quantity_rts_pack_method' => env('ALIEXPRESS_ASF_LOCAL2LOCAL_SPLIT_QUANTITY_RTS_PACK_METHOD', 'aliexpress.asf.local2local.split.quantity.rts.pack'),
                'asf_platform_logistics_document_query_method' => env('ALIEXPRESS_ASF_PLATFORM_LOGISTICS_DOCUMENT_QUERY_METHOD', 'aliexpress.asf.platform.logistics.document.query'),
                'asf_platform_logistics_rts_method' => env('ALIEXPRESS_ASF_PLATFORM_LOGISTICS_RTS_METHOD', 'aliexpress.asf.platform.logistics.rts'),
                'asf_platform_logistics_repack_method' => env('ALIEXPRESS_ASF_PLATFORM_LOGISTICS_REPACK_METHOD', 'aliexpress.asf.platform.logistics.repack'),
                'asf_local_unreachable_preference_query_method' => env('ALIEXPRESS_ASF_LOCAL_UNREACHABLE_PREFERENCE_QUERY_METHOD', 'aliexpress.asf.local.unreachable.preference.query'),
                'asf_seller_address_get_method' => env('ALIEXPRESS_ASF_SELLER_ADDRESS_GET_METHOD', 'aliexpress.asf.seller.address.get'),
                'asf_local_unreachable_preference_update_method' => env('ALIEXPRESS_ASF_LOCAL_UNREACHABLE_PREFERENCE_UPDATE_METHOD', 'aliexpress.asf.local.unreachable.preference.update'),
                'asf_local2local_transfer_to_offline_method' => env('ALIEXPRESS_ASF_LOCAL2LOCAL_TRANSFER_TO_OFFLINE_METHOD', 'aliexpress.asf.local2local.transfer.to.offline'),
                'asf_fulfillment_package_query_method' => env('ALIEXPRESS_ASF_FULFILLMENT_PACKAGE_QUERY_METHOD', 'aliexpress.asf.fulfillment.package.query'),
                'asf_local_supply_shipping_service_get_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_SHIPPING_SERVICE_GET_METHOD', 'aliexpress.asf.local.supply.shipping.service.get'),
                'asf_local_supply_batch_declareship_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_BATCH_DECLARESHIP_METHOD', 'aliexpress.asf.local.supply.batch.declareship'),
                'asf_local_supply_declareship_modify_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_DECLARESHIP_MODIFY_METHOD', 'aliexpress.asf.local.supply.declareship.modify'),
                'asf_local_supply_sub_declareship_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_SUB_DECLARESHIP_METHOD', 'aliexpress.asf.local.supply.sub.declareship'),
                'asf_local_supply_split_quantity_rts_pack_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_SPLIT_QUANTITY_RTS_PACK_METHOD', 'aliexpress.asf.local.supply.split.quantity.rts.pack'),
                'asf_local_supply_platform_logistics_document_query_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_PLATFORM_LOGISTICS_DOCUMENT_QUERY_METHOD', 'aliexpress.asf.local.supply.platform.logistics.document.query'),
                'asf_local_supply_platform_logistics_rts_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_PLATFORM_LOGISTICS_RTS_METHOD', 'aliexpress.asf.local.supply.platform.logistics.rts'),
                'asf_local_supply_platform_logistics_repack_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_PLATFORM_LOGISTICS_REPACK_METHOD', 'aliexpress.asf.local.supply.platform.logistics.repack'),
                'asf_local_supply_seller_address_get_method' => env('ALIEXPRESS_ASF_LOCAL_SUPPLY_SELLER_ADDRESS_GET_METHOD', 'aliexpress.asf.local.supply.seller.address.get'),
                'local_service_product_stocks_update_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_STOCKS_UPDATE_METHOD', 'aliexpress.local.service.product.stocks.update'),
                'local_service_product_stocks_query_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_STOCKS_QUERY_METHOD', 'aliexpress.local.service.product.stocks.query'),
                'local_service_products_list_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCTS_LIST_METHOD', 'aliexpress.local.service.products.list'),
                'local_service_product_prices_edit_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_PRICES_EDIT_METHOD', 'aliexpress.local.service.product.prices.edit'),
                'local_service_product_post_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_POST_METHOD', 'aliexpress.local.service.product.post'),
                'local_service_product_edit_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_EDIT_METHOD', 'aliexpress.local.service.product.edit'),
                'local_service_product_query_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_QUERY_METHOD', 'aliexpress.local.service.product.query'),
                'local_service_product_status_update_method' => env('ALIEXPRESS_LOCAL_SERVICE_PRODUCT_STATUS_UPDATE_METHOD', 'aliexpress.local.service.product.status.update'),
                'product_lookup_param' => env('ALIEXPRESS_PRODUCT_LOOKUP_PARAM', 'product_id'),
                'timeout' => (int) env('ALIEXPRESS_REQUEST_TIMEOUT', 20),
            ],
        ],
    ],

];
